#!/bin/bash
# Bash Module
#
# Contains routines we use to help flesh out our additionals.

# Dependencies
depend_procedure core automatic

customizer_system_prep ()
{
  # <!-- begin_system_prep = Rubyists, LLC. Default Build -->
  # Create and populate a directory with git pull of all our required files going forward.
  BUILD_CONFIG_DIR="/home/arch/tcc_arch_installer/rubyists"
  cd $BUILD_CONFIG_DIR/default_build

  # Configure where the being-built install is.
  # We use the installer's var_TARGET_DIR variable as that should be where the new_install system is mounted.
  echo "Installer sees NEW_SYSTEM's mount as: ${var_TARGET_DIR}"

  # Configure our preferred, minimalistic, sudoers file
  # Removing here ensures sudo package has no reason to fail.
  if [ -f "$var_TARGET_DIR/etc/sudoers" ]; then
    rm -f $var_TARGET_DIR/etc/sudoers
  fi

	# Create our own sudoers file, and ensure perms and ownerships
  echo "root ALL=(ALL) ALL" > ./sudoers
  echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> ./sudoers
  mv -f ./sudoers $var_TARGET_DIR/etc/sudoers
  chmod 0440 $var_TARGET_DIR/etc/sudoers
  chown root:root $var_TARGET_DIR/etc/sudoers

  # Install our network and pacman config into the chroot
	#
	# First the files we need
  cp $BUILD_CONFIG_DIR/default_build/root-image/etc/rc.conf $var_TARGET_DIR/etc/
  cp $BUILD_CONFIG_DIR/default_build/root-image/etc/resolv.conf $var_TARGET_DIR/etc/
  cp $BUILD_CONFIG_DIR/default_build/root-image/etc/pacman.conf $var_TARGET_DIR/etc/
	# Now the directories we need
  cp -R $BUILD_CONFIG_DIR/default_build/root-image/etc/network.d $var_TARGET_DIR/etc/
  cp -R $BUILD_CONFIG_DIR/default_build/root-image/etc/pacman.d $var_TARGET_DIR/etc/

  # Make sure root owns the replaced files. default ownership is root:root, perms are 644.
  echo "NOTE - setting permissions on replaced files"
  # First the directories
  chmod 755 $var_TARGET_DIR/etc/pacman.d
  chmod 755 $var_TARGET_DIR/etc/network.d
  chown -R root:root $var_TARGET_DIR/etc/pacman.d
  chown -R root:root $var_TARGET_DIR/etc/network.d

  # Now the files
  for name in {etc/rc.conf,etc/resolv.conf,etc/pacman.conf,etc/pacman.d/mirrorlist,etc/network.d/rubyists-ethernet}; do
    chown root:root $var_TARGET_DIR/$name
    chmod 644 $var_TARGET_DIR/$name
  done

  # This will get rebuilt anyways and stops potential errors
  if [ -f "$var_TARGET_DIR/etc/profile.d/locale.sh" ]; then
    rm $var_TARGET_DIR/etc/profile.d/locale.sh
  fi

  # Update chroot's pacman. Install fakeroot, tmux, git, and sudo in chroot tree. Create final sudoers file.
  /usr/sbin/chroot --userspec=root:root /mnt/ /usr/bin/pacman -Syu --noconfirm
  /usr/sbin/chroot --userspec=root:root /mnt/ /usr/bin/pacman -S fakeroot tmux git devtools sudo --needed --noconfirm

  # Now sync and update the package lists, then upgrade the system.
  /usr/sbin/chroot --userspec=root:root /mnt/ pacman -Syy --noconfirm
  /usr/sbin/chroot --userspec=root:root /mnt/ pacman --noprogressbar --noconfirm --logfile $HOME/pacman_install_and_upgrade.log -Syu
  # <!-- end_system_prep
}

customizer_install_support_packages ()
{
  # <!-- begin_install_support_packages = Rubyists, LLC. Default Build -->
  # Change to 'callcenter'. All further work should be owned by 'callcenter'
  cp -R $BUILD_CONFIG_DIR/default_build/root-image/etc/pacman.d $var_TARGET_DIR/etc/
  cp $BUILD_CONFIG_DIR/default_build/root-image/etc/pacman.conf $var_TARGET_DIR/etc/
  chmod 755 $var_TARGET_DIR/etc/pacman.d
  chown -R root:root $var_TARGET_DIR/etc/pacman.d
  chown root:root $var_TARGET_DIR/etc/pacman.conf

  # Set up ssh access to 'callcenter', we;ll add the actual user when we chroot.
  # Physically ensure proper owner+perms are set correctly.
  echo "Copying 'callcenter' user into place.."
  /bin/cp -R $BUILD_CONFIG_DIR/default_build/root-image/home/callcenter $var_TARGET_DIR/home/
  /bin/chmod 700 $var_TARGET_DIR/home/callcenter/.ssh
  /bin/chmod 600 $var_TARGET_DIR/home/callcenter/.ssh/authorized_keys

  # Now, chroot and execute within the context of the new system.
  echo "STARTING CHROOT"
  # Add 'callcenter' user now that we've populated it's homedir with the authorized_keys file.
  /usr/sbin/chroot --userspec=root:root /mnt/ /usr/sbin/useradd -g users -G wheel -s /bin/bash callcenter
  # Ensure that callcenter owns it's homedir and files, then su to callcenter to start pkg builds.
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/chown -R callcenter:users /home/callcenter

  # NOTE: This is where masterkorp's work goes. This is where we install and configure packages.
  #
  # Expect 'callcenter'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c whoami

  # Configure filesystem for package builds
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'mkdir $HOME/builds'
  # chroot --userspec=root:root /mnt/ su -l callcenter -c cd $HOME/builds

  # Get all needed AUR packages for our configuration.
  # TODO: Change this so a sourced file of packages we can pass to a looped $(wget $url)
	# Make sure we have a proper pacman
	cp $BUILD_CONFIG_DIR/default_build/root-image/etc/pacman.d/mirrorlist-canada $var_TARGET_DIR/etc/pacman.d/mirrorlist
	/usr/sbin/chroot --userspec=root:root /mnt/ pacman -Syy --noconfirm
	
	# Now we start the builds themselves. Pacman should be happy now, dang it!
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'echo "**** STARTING BUILDS ****"'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds ; wget http://aur.archlinux.org/packages/fg/fgetty/fgetty.tar.gz'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds ; wget http://aur.archlinux.org/packages/ru/runit-dietlibc/runit-dietlibc.tar.gz'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds ; wget http://aur.archlinux.org/packages/ru/runit-run/runit-run.tar.gz'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds ; wget http://aur.archlinux.org/packages/ru/runit-services/runit-services.tar.gz'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds ; wget http://aur.archlinux.org/packages/sv/sv-helper/sv-helper.tar.gz'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds ; wget http://aur.archlinux.org/packages/so/socklog-dietlibc/socklog-dietlibc.tar.gz'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds ; wget http://aur.archlinux.org/packages/fr/freeswitch-git/freeswitch-git.tar.gz'

  # Now extract, build, create, and install AUR packages we grabbed
  # TODO: Change this to a sourced, ordered, file for package install
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds ; for name in ./*.gz ; do tar -xzvf $name ; done'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/chown -R callcenter:users /home/callcenter/builds
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/mknod /dev/null c 1 3
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/chmod 0666 /dev/null
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds/fgetty ; makepkg -si --noconfirm'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds/runit-dietlibc ; makepkg -si --noconfirm'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds/runit-run ; makepkg -si --noconfirm'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds/socklog-dietlibc ; makepkg -si --noconfirm'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds/runit-services ; makepkg -si --noconfirm'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds/sv-helper ; makepkg -si --noconfirm'
  /usr/sbin/chroot --userspec=root:root /mnt/ /bin/su -l callcenter -c 'cd $HOME/builds/freeswitch-git ; makepkg -si --noconfirm'

  # Mark that we completed successfully
  return 0
  # <!-- end_install_support_packages -->
}

customizer_configure_runit_services_and_logs ()
{
  # <!-- begin_configure_runit_services_and_logs = Rubyists, LLC. Default Build -->
  # Create default runit services
  /usr/sbin/chroot --userspec=root:root /mnt/ ln -s /etc/sv/sshd /service/sshd
  /usr/sbin/chroot --userspec=root:root /mnt/ ln -s /etc/sv/cron /service/cron

  # Set up socklog
  /usr/sbin/chroot --userspec=root:root /mnt/ socklog-conf unix root daemon
  /usr/sbin/chroot --userspec=root:root /mnt/ socklog-conf klog root daemon
  /usr/sbin/chroot --userspec=root:root /mnt/ ln -s /etc/sv/socklog-unix /service/socklog-unix
  /usr/sbin/chroot --userspec=root:root /mnt/ ln -s /etc/sv/socklog-klog /service/socklog-klog

  # Enable freeswitch as a default service last always. Not required, just good form that last service enabled
  # be that which everything else was installed as support for.
  /usr/sbin/chroot --userspec=root:root /mnt/ ln -s /etc/sv/freeswitch /service/freeswitch 

  # Mark that we completed successfully
  return 0
  # <!-- end_configure_runit_services_and_logs -->
}
